name = "BettingGamesJL"
uuid = "c881f083-b779-4f41-a1e2-4d9d4f32d50b"
authors = ["TheLoggicalOne <TheLoggicalOne@Gmail.Com>"]
version = "0.1.0"

[deps]
ReinforcementLearning = "158674fc-8238-5cab-b5ba-03dfc80d1318"
